[package]
name = "rust_x"
version = "0.1.0"
authors = ["MarshallRawson <marshallrawson@ufl.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
