#!/usr/bin/env bash
test -z $ANDROID_ROBOTICS_REPO_DIR && echo "ANDROID_ROBOTICS_REPO_DIR not set!" && exit 1
set -euo pipefail

adb push $ANDROID_ROBOTICS_REPO_DIR/Rust/rust_x/target/armv7-linux-androideabi/debug/rust_x /data/local/tmp
